### ISSUE TITLE
the parser don't return the last cluster

### ISSUE THREAD

**Issue by baimingze** [spectra-cluster/spectra-cluster-py#1]
For the "tests\test.clustering" file, the parser returns two same  cluster at last, the last second one:  (id=dcc104e8-3da7-4b27-bc3e-b497d88f2efc ), 
rather than the really last one:
(id=25ed3015-f2d8-4df1-ac96-c23076c96bfe).

**Comment by jgriss** [comment]
@baimingze Thanks a lot for spotting this! Should be fixed now.

Best regards,
Johannes
