### ISSUE TITLE
Shared spectrum bug [Cluster_comparer]

### ISSUE THREAD

**Issue by enriiquee** [spectra-cluster/spectra-cluster-py#2]
Hello! 

I'm using your code in order to compare different releases of PRIDE Cluster. The problem that I've got is when I compare two files (In this case, the same file), I got these example results:

stars No.	32	in file with less(or equal) clusters: file1
starlets No.	32	in file with more(or equal) clusters: file0
identical cluster No.	32	between them
**spectrum No	133	in stars
spectrum No	133	in starlets 
shared spectrum No	141	between them
shared spectrum percent	106.02	in stars
shared spectrum percent	106.02	in starlets**

As you can see, those results do not make sense because I've got the same spectrum number, but in shared spectrum appear 141 between them. 

Could you please fix this bug or telling me how to fix it?

Thank you very much and sorry for the inconveniences.

**Comment by jgriss** [comment]
Hi,

Thanks for reporting this! As you've seen, this tool is still in a -dev branch and highly experimental. Actually, we'll probably have to rewrite it completely but there's currently now time for it.

In case you're interested in contributing to this that'd be great. The main change that's needed is to move the whole network comparison to the **networkx** package. That would make everything a lot cleaner.

Could you give me a few details about your files: What's the number of total spectra (ie `grep -c "^SPEC" your_file.clustering`)? How many clusters are there that only contain a single spectrum?

Alternatively, could you maybe just send the file to me directly? 

Thanks!

Johannes

**Comment by ypriverol** [comment]
Hi @jgriss:
 As you know @enriiquee is working in a QC pipeline for PRIDE Cluster. The main idea is to been able 
 trace the difference between one run and another. If you remember it was one of our main threads in 
 confluence. @enriiquee  had finished the exported to Uniprot including the comparison between 
 releases. Also ha has finished the first step when we consume the spectra from cluster, he can compare 
 releases number of spectra, peptides, unique peptides, modifications, etc. I will share with you privately 
 the results. But all the code is documented on confluence.   

 We just moved to the final results and decided to test the @baimingze & you code. In order to 
 coordinate this better. I propose that @enriiquee send you the files and you can tested. what do you 
 think about @enriiquee implement the movement to the **networkx** package. 

Regards 
Yasset

**Comment by enriiquee** [comment]
Hello  @jgriss ,
Thank you for your answer. 

As Yasset said, my main goal is to compare different releases. Before this, I've tested small files produced in the last release in order to see if everything is correct.

To carry out this, I merge  8 output files using `cat clastering_files_release1/*.clustering >> total.clustering`. In this link you can see the folder with the 8 output files and the merged file (total.clustering) [https://www.dropbox.com/sh/k24axxzwlgy57wu/AACc6uW34-aszni5Ks2iNtQCa?dl=0](url)

After this, I checked the Cluster_comparer using the same file as a <results1.clustering,results2.clustering> , obtaining the results that I put you at the beginning of this page.

Regards
Enrique Pérez

**Comment by baimingze** [comment]
Hi @enriiquee , I have checked the code.  The reason of this bug is like this:

When you compare one cluster with it self, normally you will get the 100% sharing spectra. But if this cluster contains one spectrum repeatly, the result goes wired. For example,  Cluster(spectrum1, spectrum1) compared to it self, will get 4 shared spectrum.

In your test file, you can find this cluster:
```
=Cluster=
id=d2cedeba-2abf-47f2-9c4c-dbd55046ed31
av_precursor_mz=3949.598
av_precursor_intens=1.0
sequence=[TGTAEMSSILEER:1,VAPEEHPVLLTEAPLNPK:1]
consensus_mz=125.103,139.091,153.068,196.102,199.182,253.186,260.198,263.102,331.215,346.215,373.204,386.155,434.215,438.238,446.224,452.694,497.234,548.777,567.748,569.336,570.316,599.811,648.806,656.840,666.346,673.340,685.840,751.869,758.894,776.882,780.875,784.401,802.715,811.887,855.988,881.944,937.955,962.027,980.488,989.980,995.989,1001.971,1024.855,1030.907,1055.130,1085.035,1118.148,1126.177,1146.013,1195.094,1198.032,1246.602,1284.199,1294.109,1324.156,1331.165,1334.147,1352.018,1363.725,1407.654,1425.763,1450.669,1488.665,1498.742,1509.796,1544.711,1545.201,1570.184,1572.761,1612.240,1647.750,1685.854,1708.823,1758.846,1769.818,1794.876,1797.782,1864.877,1923.073,2669.309,2679.257,3108.522
consensus_intens=9.72,14.88,22.26,18.32,267.84,51.16,52.14,74.15,44.52,89.53,197.99,85.59,30.74,32.47,35.05,9.84,126.79,69.48,32.96,242.26,134.53,124.94,30.62,19.43,94.94,36.03,33.45,66.16,69.48,44.76,63.33,58.91,11.43,33.20,20.17,39.35,82.02,152.24,56.20,74.64,61.49,18.81,42.55,742.32,19.55,23.74,129.86,26.44,41.93,18.57,18.94,63.70,22.01,12.17,22.26,56.45,11.81,13.90,90.63,33.20,179.54,15.13,34.92,13.53,14.88,161.34,210.90,16.97,13.28,14.26,13.65,21.77,24.47,43.41,10.58,11.19,11.81,20.04,10.45,50.30,120.51,23.49
SPEC    PRD000523;PRIDE_Exp_Complete_Ac_18464.xml;spectrum=30808    true    VAPEEHPVLLTEAPLNPK  3949.5984   1   9606        0.8957048647927288
SPEC    PRD000523;PRIDE_Exp_Complete_Ac_18465.xml;spectrum=30808    true    TGTAEMSSILEER   3949.5984   1   9606        0.8957048647927288
 ```

**Comment by baimingze** [comment]
Hi @enriiquee , very interesting finding, I have checked the code. The reason of this bug is like this:

When one spectrum appears in different clusters, the shared info goes wired.

For example: 
In file1:  Cluster1(spectrum1, spectrum2), Cluster2(spectrum2, spectrum3)  compared 
to file2: Cluster1(spectrum1, spectrum2), Cluster2(spectrum2, spectrum3)

there are only 3 spectra, but the shared  spectra we got in result is 5.

In your test file, you can find the repeated spectra:

```
grep SPEC  clustering_files/total.clustering | sort
...
SPEC	PRD000681;PRIDE_Exp_Complete_Ac_22493.xml;spectrum=473	true	LHDEEIQELQAQIQEQHVQIDMDVSKPDLTAALR	3940.9756	1	9913		0.7904106685294755
SPEC	PRD000681;PRIDE_Exp_Complete_Ac_22493.xml;spectrum=473	true	LHDEEIQELQAQIQEQHVQIDMDVSKPDLTAALR	3940.9756	1	9913		0.9815691199409294
...

SPEC	PRD000681;PRIDE_Exp_Complete_Ac_22494.xml;spectrum=298	true	LHDEEIQELQAQIQEQHVQIDMDVSKPDLTAALR	3940.9565	1	9913		0.7701064085889492
SPEC	PRD000681;PRIDE_Exp_Complete_Ac_22494.xml;spectrum=298	true	LHDEEIQELQAQIQEQHVQIDMDVSKPDLTAALR	3940.9565	1	9913		0.8606781515744031

```

And in the STD output, you also can get a warning:
```
!!!!!!!!!!!!Becareful, total spectra No is less than Shared Spectra with starlets
with star f73788a7-0556-43bd-8607-a6f6dd234d82  2is less than3
```

Do you have any suggestions on the right way to deal with this "spectra repeat  in different clusters" situation? Any comments are welcome, thanks!

**Comment by jgriss** [comment]
Hi @enriiquee how did you create the results in the first place?

The spectra-cluster algorithm never duplicates spectra. Did you concatenate repeated clustering results of the same files?

@baimingze As mentioned above, these repeated spectra normally cannot occur. So this must be an issue in the creation of the test files. There's no need to adapt the code for this.

**Comment by enriiquee** [comment]
Hi @jgriss .

@ypriverol and I think this may be because submitters have submitted to PRIDE the same file several times and when we run Haddop Cluster, the algorithm takes both files. 
I concatenated different files and none of them were repeated files. 

We think that some possible solutions to deal with this would be:

- If there are repeated spectrum, count them as if they were only 1.
or
- If there are repeated spectrum, delete one.

What do you think about these possible solutions?
Regards

**Comment by jgriss** [comment]
Hi @enriiquee ,
I am not sure that this explains it. The spectrum ids are generated from the original PRIDE file (these are all old PRIDE submissions) and the index of the spectrum within this file. If the submitter had submitted the same data twice it would just have been duplicated.

In this pipeline though, all data from the PRIDE submissions were written to a single XML file. Therefore, every spectrum is present only once in these files. The duplication must have happend somewhere else.

But based on the title string (the id is stored in the MGF titles) you should be able to find out which MGF files contain the duplicate spectra.

**Comment by enriiquee** [comment]
Hi again @jgriss 
In order to check the clustering files that I merged, I used  `grep` option with the pattern repeated. `grep "PRD000681;PRIDE_Exp_Complete_Ac_22493.xml;spectrum=473" *`.

And I obtained this: 

`clusteringBin3940.clustering:SPEC	PRD000681;PRIDE_Exp_Complete_Ac_22493.xml;spectrum=473	true	LHDEEIQELQAQIQEQHVQIDMDVSKPDLTAALR	3940.9756	19913		0.9815691199409294
clusteringBin3941.clustering:SPEC	PRD000681;PRIDE_Exp_Complete_Ac_22493.xml;spectrum=473	true	LHDEEIQELQAQIQEQHVQIDMDVSKPDLTAALR	3940.9756	19913		0.7904106685294755

total.clustering:SPEC	PRD000681;PRIDE_Exp_Complete_Ac_22493.xml;spectrum=473	true	LHDEEIQELQAQIQEQHVQIDMDVSKPDLTAALR	3940.9756	1	9913	0.9815691199409294
total.clustering:SPEC	PRD000681;PRIDE_Exp_Complete_Ac_22493.xml;spectrum=473	true	LHDEEIQELQAQIQEQHVQIDMDVSKPDLTAALR	3940.9756	1	9913	0.7904106685294755
`
As you can see, they've got the same spectrum number but different scores... 0.98156 and 0.79041

**Comment by baimingze** [comment]
Hi Enrique,

Based on my understanding on @jgriss <https://github.com/jgriss> Johannes's
latest comment,  if we can check the original spectrum from the input MGF
files to see it is redundant or not, then we can make things clear.
I guess this info may help us locating the reason : from input files or
inside the clustering algorithm?

Best reagards,
Mingze

**Comment by jgriss** [comment]
Hi @enriiquee,

As @baimingze pointed out, you'd need to check the MGF files. The clustering algorithm never duplicates spectra. Therefore, your MGF files apparently contain spectra with the same id twice.

Once you've located in which MGF files the duplicate spectra occur you also need to check whether they are actually identical (based on the peaks) or different spectra. In the first case, you should remove any duplicate spectra prior to clustering. In the second case, you would need to make sure that every spectrum gets a unique id before clustering.

Best regards,
Johannes

**Comment by enriiquee** [comment]
Hello @jgriss, @baimingze and @ypriverol 
After a deep investigation I found some bugs in the MGF files. These bugs will be fixed in the next release of PRIDE Cluster. In order to carry out the pipeline that was order me, I have written a script that allows deleting duplicates, one of them is written in perl (faster) and another written in Python (slower). I let you here if you are interested: [https://github.com/enriiquee/duplicate_remover/blob/master/duplicate_remover2.py](url)

Regards
